name: Daily Sync

on:
  # Runs at 02:00 UTC (7 PM US/Pacific).
  schedule:
    - cron: '0 19 * * *'
  # Also allows manual triggering
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Latest Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Fetch the latest release for Linux AMD64
          gh release download --repo ${{ github.repository }} --pattern "*linux-amd64.tar.gz"
          tar -xzf mbdb-linux-amd64.tar.gz
          chmod +x mbdb

      - name: Run MyBrightDay Download
        env:
          # Inject repository secrets into environment variables
          MYBRIGHTDAY_EMAIL: ${{ secrets.MYBRIGHTDAY_EMAIL }}
          MYBRIGHTDAY_PASSWORD: ${{ secrets.MYBRIGHTDAY_PASSWORD }}
          GOOGLE_PHOTOS_TOKEN_SECRET: ${{ secrets.GOOGLE_PHOTOS_TOKEN_SECRET }}
        run: |
          ./mbdb download \
            --date "-7:+3" \
            --local.enabled=false \
            --googlephotos.enabled=true \
            --logging.level=INFO \
            --logging.format=text-full
